version: '3'
services:
  web:
    image: nginx
    ports:
      - "8084:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../html:/var/www/html
    networks:
      - web
  app:
    build: .
    image: boyz-app
    working_dir: /var/www/html
    volumes:
      - ../html:/var/www/html
    networks:
      - web
networks:
  web: